_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
agent_params:
    value:
        batch_size: 64
        epsilon_decay: 0.995
        epsilon_min: 0.01
        gamma: 0.95
        learning_rate: 0.001
        memory_size: 10000
        target_update_freq: 10
env_config:
    value:
        market_volatility: 0.03
        max_steps: 50
episodes:
    value: 200
eval_freq:
    value: 25
max_steps:
    value: 50
save_freq:
    value: 50
